### ISSUE TITLE
Add processing notes to Redmine via custom JS/CSS

### ISSUE THREAD

**Issue by ashepherd** [BCODMO/redmine_aws#1]
Based on team discussions, Redmine seems the appropriate place. Data managers would like a section appearing underneath "Related Files" for this processing notes with a possible toggle for show/hide these notes.

We can inject custom JS and CSS into Redmine using built-in themes or plugins
https://www.redmine.org/projects/redmine/wiki/howto_create_a_custom_redmine_theme
https://www.redmine.org/plugins/redmine_custom_css
https://www.redmine.org/plugins/redmine_custom_js

With these we could manipulate the DOM to take a custom field in Redmine, place with underneath "Related Files" and add show/hide feature. 

FUTURE, separate issue: Additionally, we can include a link to some reporting feature that uses the Submission ID custom field to display a report. (see DM README template for legacy processing notes)

```
00_README.txt (example: /data302/Vermetids_Corals/00_README.txt)
Project: [project name]
===================REPEAT BELOW AS NEEDED==========================

Data Manager: [Full Name] 
Submission Date: 
PI: 
Submitter: 
Award: 
Redmine ticket: https://kato.bco-dmo.org/issues/ 

RESTRICTED? 

Original data file(s) path and name: 
[short name description] 
[full path to directory] 
[relative path from directory above to files] 

Working file(s) path and name: 
[short name description] 
[full path to directory]
 [relative path from directory above to files] 

Final dataset files: This is a known thing based on the dataset ID and data version number but is it possible to expose it on the redmine issue?

Pipeline: 

Data_docs path, filenames and url:

 Final DATA path: 
[short name description]
 
JGOFS DATA url: 
[short name description]

 OSPREY URL:
 [short dataset name description] 
[url]
================================================ 
Processing notes: 
[date you did processing]:
Questions: [include resolution if applicable]
```

**Comment by adyork** [comment]
@cschloer / @ashepherd  this discussion came up in today's meeting.  

We had started this conversation about adding the processing notes to redmine in submission. 
 I'll close it there since it makes more sense in this repo. https://github.com/BCODMO/bcodmo_submission/issues/86
 
I think after my last comment in https://github.com/BCODMO/bcodmo_submission/issues/86 about it being cumbersome to put them in the normal "Description" section you (@cschloer) did some testing of how to add a dedicated field for "Processing Notes" and if memory serves some intricacies of that were whether you could get it to be full width , not half column.  Do you remember that?  Can we revisit if that is possible? 

And I think we discussed making the field a set number of rows by default with expandability on drag or click.  So that it doesn't push the rest of the content down too much but is still available when you need to see everything.

And this is the list we made at a meeting of when and why we take notes and need to read notes which were a driver of deciding where to put readme notes in future. [2021-01-28 Lab Meeting](https://docs.google.com/document/d/1Lxy_zt-Y9a8XTLiE6KwrfsGRjzVaIhjsFgC3rIWBu24/edit#bookmark=id.f9r9msh9lzbg)

**Comment by adyork** [comment]
Topic summary from our [DM meeting today](https://docs.google.com/document/d/1EzavSOfPfaWRG6rieHMgzsYMj0TBEFky-WmqbnAyBTQ/edit#heading=h.gelx1o5y51xw) :

If our goal is to do at least as good as our previous architecture, then that would be met by supporting plain text only which is what our REAME files on the server are now.  
 
 This issue will become more pressing once we move to new architecture where we only make folders on the server in cases of working/scratch space.  Our current README files are in the project folders we make for all submissions there.  But we won't be doing that anymore for "normal" datasets so we need an official home for Submission and Dataset-level processing notes.

We mentioned that in the best of all possible worlds it would be great to allow us to wysiwyg the notes, and allow things like pasting images like you can do in a google doc or github, and allow text color which is currently lost when we paste email correspondence that uses that to distinguish questions and answers from submitters.

But that may be too complicated to support now? Especially if we are going with a Redmine field.  While you can add images to a redmine issue it is as an attachment or link to an image somewhere else and is time consuming to manage and format within the redmine text. 

Some DMs now prefer to take notes in google docs and for those cases, we discussed that they will be pdf'ing and attaching the notes to redmine which will be time consuming and inflexible but is a way to get more feature rich notes and insure everyone can access them.

**Comment by adyork** [comment]
We decided since every change to the field blows up the issue changelog to not use this.  We are going to put a template for our processing notes in the issue notes manually.
